def returntags():
    return '''romance
    young-adult
    fantasy
    science-fiction
    children
    historical-fiction
    mystery
    horror
    gay
    paranormal
    historical-romance
    thriller
    contemporary
    classics
    crime
    humor
    suspense
    dystopia
    adventure
    african-american
    asian-literature
    biblical-fiction
    chick-lit
    christian-fiction
    civil-war
    cyberpunk
    dark
    drama
    fantasy-romance
    folklore
    french-literature
    high-school
    historical-mystery
    latin-american-literature
    legal-thriller
    gay-fiction
    lesbian-fiction
    lgbt
    literary-fiction
    high-fantasy
    low-fantasy
    lovecraftian
    urban-fantasy
    supernatural
    futuristic
    magic
    medieval
    military-fiction
    modern-classics
    mystery-thriller
    mythology
    psychological-thriller
    pulp-noir
    punk
    queer-lit
    realistic-fiction
    regency-romance
    russian-literature
    romantic-suspense
    slice-of-life
    space-opera
    steampunk
    spy-thriller
    sports-romance
    supernatural-romance
    time-travel
    tragedy
    victorian
    westerns
    world-war-i
    world-war-ii'''.replace("   ", "").replace(" ", "").split("\n")