def returntags():
    return '''romance
    young-adult
    fantasy
    science-fiction
    children
    historical-fiction
    mystery
    horror
    gay
    paranormal
    historical-romance
    thriller
    contemporary
    classics
    crime
    humor
    suspense
    dystopia
    adventure
    african-american
    asian-literature
    Biblical-fiction
    Chick-lit
    Christian-fiction
    Civil-war
    Cyberpunk
    Dark
    Drama
    Fantasy-romance
    Folklore
    French-literature
    High-school
    Historical-mystery
    Latin-american-literature
    Legal-thriller
    Gay-fiction
    Lesbian-fiction
    Lgbt
    Literary-fiction
    High-fantasy
    Low-fantasy
    Lovecraftian
    Urban-fantasy
    Supernatural
    Futuristic
    Magic
    Medieval
    Military-fiction
    Modern-classics
    Mystery-thriller
    Mythology
    Psychological-thriller
    Pulp-noir
    Punk
    Queer-lit
    Realistic-fiction
    Regency-romance
    Russian-literature
    Romantic-suspense
    Slice-of-life
    Space-opera
    Steampunk
    Spy-thriller
    Sports-romance
    Supernatural-romance
    Time-travel
    Tragedy
    Victorian
    Westerns
    World-war-i
    world-war-ii'''.replace("   ", "").replace(" ", "").split("\n")